# Reads the keymap from `keymap.yaml` (keymap-drawer YAML) and generates
# QMK and ZMK keymaps. Firmware-independent labels live in the YAML; this
# script is the only place that maps them to ZMK/QMK codes.
import os.path
import sys
from collections import namedtuple

import yaml

HEADER = "// This file is automatically generated from keymap.yaml\n"

# Maps labels from keymap.yaml to key press codes in ZMK and QMK.
# "LABEL": ("ZMK CODE", "QMK CODE")
KEY_PRESS_CODES = {
    # Special Keys
    "ESC": ("ESC", "KC_ESC"),
    "RET": ("RET", "KC_ENT"),
    "TAB": ("TAB", "KC_TAB"),
    "SPC": ("SPC", "KC_SPC"),
    "BKSP": ("BKSP", "KC_BSPC"),
    "CMD_RET": ("LG(RET)", "S(KC_ENT)"),
    "ALTBKSP": ("LA(BKSP)", "A(KC_BSPC)"),
    "ALT_BKSP": ("LA(BKSP)", "A(KC_BSPC)"),
    # Text Navigation Keys
    "LEFT": ("LEFT", "KC_LEFT"),
    "RIGHT": ("RIGHT", "KC_RIGHT"),
    "UP": ("UP", "KC_UP"),
    "DOWN": ("DOWN", "KC_DOWN"),
    "WORDL": ("LA(LEFT)", "A(KC_LEFT)"),
    "WORD_L": ("LA(LEFT)", "A(KC_LEFT)"),
    "WORDR": ("LA(RIGHT)", "A(KC_RIGHT)"),
    "WORD_R": ("LA(RIGHT)", "A(KC_RIGHT)"),
    "HOME": ("HOME", "KC_HOME"),
    "END": ("END", "KC_END"),
    # UI Navigation Keys
    "SPC_L": ("LC(LEFT)", "C(KC_LEFT)"),
    "SPC_R": ("LC(RIGHT)", "C(KC_RIGHT)"),
    "NXT_WIN": ("LC(F4)", "C(KC_F4)"),
    # Forward / Backwards (GUI + Bracket)
    "FWD": ("LG(LBKT)", "G(KC_LBRC)"),
    "BCK": ("LG(RBKT)", "G(KC_RBRC)"),
    # Prev / Next Tab (GUI + Shift Bracket)
    "TABL": ("LG(LS(LBKT))", "G(S(KC_LBRC))"),
    "TAB_L": ("LG(LS(LBKT))", "G(S(KC_LBRC))"),
    "TABR": ("LG(LS(RBKT))", "G(S(KC_RBRC))"),
    "TAB_R": ("LG(LS(RBKT))", "G(S(KC_RBRC))"),
    # Umlaut key
    "UML": ("LA(U)", "A(KC_U)"),
    # Symbols
    "`": ("GRAVE", "KC_GRAVE"),
    "~": ("LS(GRAVE)", "KC_TILDE"),
    "!": ("LS(N1)", "KC_EXCLAIM"),
    "@": ("LS(N2)", "KC_AT"),
    "#": ("LS(N3)", "KC_HASH"),
    "$": ("LS(N4)", "KC_DOLLAR"),
    "%": ("LS(N5)", "KC_PERCENT"),
    "^": ("LS(N6)", "KC_CIRCUMFLEX"),
    "&": ("LS(N7)", "KC_AMPERSAND"),
    "*": ("LS(N8)", "KC_ASTERISK"),
    "(": ("LS(N9)", "KC_LEFT_PAREN"),
    ")": ("LS(N0)", "KC_RIGHT_PAREN"),
    "-": ("KP_MINUS", "KC_MINUS"),
    "_": ("LS(MINUS)", "KC_UNDERSCORE"),
    "=": ("EQUAL", "KC_EQUAL"),
    "+": ("LS(EQUAL)", "KC_PLUS"),
    "[": ("LBKT", "KC_LBRC"),
    "{": ("LS(LBKT)", "KC_LCBR"),
    "]": ("RBKT", "KC_RBRC"),
    "}": ("LS(RBKT)", "KC_RCBR"),
    "\\": ("BSLH", "KC_BSLASH"),
    "|": ("LS(BSLH)", "KC_PIPE"),
    "PIPE": ("LS(BSLH)", "KC_PIPE"),
    ";": ("SEMI", "KC_SCOLON"),
    ":": ("LS(SEMI)", "KC_COLON"),
    "'": ("SQT", "KC_QUOTE"),
    '"': ("LS(SQT)", "KC_DOUBLE_QUOTE"),
    ",": ("COMMA", "KC_COMMA"),
    "<": ("LS(COMMA)", "KC_LEFT_ANGLE_BRACKET"),
    ".": ("DOT", "KC_DOT"),
    ">": ("LS(DOT)", "KC_RIGHT_ANGLE_BRACKET"),
    "/": ("FSLH", "KC_SLASH"),
    "?": ("LS(FSLH)", "KC_QUESTION"),
    # Modifiers
    "CMD": ("LGUI", "KC_LGUI"),
    "SHFT": ("LSHFT", "KC_LSFT"),
    "SHIFT": ("LSHFT", "KC_LSFT"),
    "CTRL": ("LCTRL", "KC_LCTL"),
    "ALT": ("LALT", "KC_LALT"),
}

# Maps labels from keymap.yaml to special instructions for ZMK and QMK.
SPECIAL_LABELS = {
    "BT_CLR": ("&bt BT_CLR", "KC_NO"),
    "BTCLR": ("&bt BT_CLR", "KC_NO"),
    "BT_0": ("&bt BT_SEL 0", "KC_NO"),
    "BT0": ("&bt BT_SEL 0", "KC_NO"),
    "BT_1": ("&bt BT_SEL 1", "KC_NO"),
    "BT1": ("&bt BT_SEL 1", "KC_NO"),
    "BT_2": ("&bt BT_SEL 2", "KC_NO"),
    "BT2": ("&bt BT_SEL 2", "KC_NO"),
    "BT_3": ("&bt BT_SEL 3", "KC_NO"),
    "BT3": ("&bt BT_SEL 3", "KC_NO"),
}

# Layer hold labels → layer index (order of layers in keymap.yaml).
LAYER_LABELS = {
    "RSE": 1,
    "RAISE": 1,
    "LWR": 2,
    "LOWER": 2,
    "HYP": 3,
    "HYPER": 3,
    "ADJ": 4,
    "ADJUST": 4,
    "MOU": 5,
    "MOUSE": 5,
}

TapHold = namedtuple("TapHold", ("tap", "hold"))
Combo = namedtuple("Combo", ("a", "b", "result"))
Layer = namedtuple("Layer", ("name", "rows", "combos"))


def normalize_label(label):
    if label is None:
        return ""
    return str(label).strip()


def lookup_key(label):
    """Return uppercase lookup key for maps; preserve single-char symbols."""
    label = normalize_label(label)
    if not label:
        return ""
    if len(label) == 1:
        return label.upper() if label.isalpha() else label
    return label.upper().replace("-", "_")


################################################################################
# Mapping to QMK


def _suffix_after_prefix(label, key, prefix):
    """Return the label portion after a CMD_/HYP_-style prefix."""
    if "_" in label:
        return label.split("_", 1)[1]
    return key[len(prefix) :]


def get_qmk_key_press_code(label):
    label = normalize_label(label)
    if not label:
        return None
    key = lookup_key(label)
    if key.startswith("CMD_"):
        return f"G({get_qmk_key_press_code(_suffix_after_prefix(label, key, 'CMD_'))})"
    if key.startswith("HYP_"):
        return (
            f"G(S(A(C({get_qmk_key_press_code(_suffix_after_prefix(label, key, 'HYP_'))}))))"
        )
    if len(label) == 1 and (label.isalpha() or label.isdigit()):
        return f"KC_{label.upper()}"
    if key in KEY_PRESS_CODES:
        return KEY_PRESS_CODES[key][1]
    if label in KEY_PRESS_CODES:
        return KEY_PRESS_CODES[label][1]
    return None


def map_key_label_to_qmk(label):
    code = get_qmk_key_press_code(label)
    if code:
        return code
    key = lookup_key(label)
    if key in LAYER_LABELS:
        return f"MO({LAYER_LABELS[key]})"
    if key in SPECIAL_LABELS:
        return SPECIAL_LABELS[key][1]
    if not normalize_label(label):
        return "KC_NO"
    raise KeyError(f"Cannot map label {label!r} to qmk.")


def map_tap_hold_key_to_qmk(tap, hold):
    if not hold:
        return map_key_label_to_qmk(tap)
    if not tap:
        return map_key_label_to_qmk(hold)

    tap_code = get_qmk_key_press_code(tap)
    hold_code = get_qmk_key_press_code(hold)
    hold_key = lookup_key(hold)
    if tap_code:
        if hold_code:
            hold_code = hold_code.replace("KC_", "MOD_")
            return f"MT({hold_code},{tap_code})"
        if hold_key in LAYER_LABELS:
            return f"LT({LAYER_LABELS[hold_key]},{tap_code})"
    raise KeyError(f"Cannot map thumb key ({tap}, {hold}) to qmk.")


def generate_qmk_combo(combo):
    if not combo:
        return ("KC_NO", "KC_NO")
    return (
        ", ".join((map_key_label_to_qmk(combo.a), map_key_label_to_qmk(combo.b))),
        map_key_label_to_qmk(combo.result),
    )


def generate_qmk_layer(layer):
    rows = []
    for row in layer.rows:
        rows.append(
            ", ".join(map_tap_hold_key_to_qmk(tap, hold) for tap, hold in row)
        )
    return ",\n".join(rows)


################################################################################
# Mapping to ZMK


def get_zmk_key_press_code(label):
    label = normalize_label(label)
    if not label:
        return None
    key = lookup_key(label)
    if key.startswith("CMD_"):
        return f"LG({get_zmk_key_press_code(_suffix_after_prefix(label, key, 'CMD_'))})"
    if key.startswith("HYP_"):
        return (
            f"LA(LS(LC(LG({get_zmk_key_press_code(_suffix_after_prefix(label, key, 'HYP_'))}))))"
        )
    if label.isalpha() and len(label) == 1:
        return label.upper()
    if label.isdigit() and len(label) == 1:
        return f"N{label}"
    if key in KEY_PRESS_CODES:
        return KEY_PRESS_CODES[key][0]
    if label in KEY_PRESS_CODES:
        return KEY_PRESS_CODES[label][0]
    return None


def map_key_label_to_zmk(label):
    code = get_zmk_key_press_code(label)
    if code:
        return f"&kp {code}"
    key = lookup_key(label)
    if key in LAYER_LABELS:
        return f"&mo {LAYER_LABELS[key]}"
    if key in SPECIAL_LABELS:
        return SPECIAL_LABELS[key][0]
    if not normalize_label(label):
        return "&trans"
    raise KeyError(f"Cannot map label {label!r} to zmk.")


def map_tap_hold_key_to_zmk(tap, hold):
    if not hold:
        return map_key_label_to_zmk(tap)
    if not tap:
        return map_key_label_to_zmk(hold)

    tap_code = get_zmk_key_press_code(tap)
    hold_code = get_zmk_key_press_code(hold)
    hold_key = lookup_key(hold)
    if tap_code:
        if hold_code:
            return f"&mt_ {hold_code} {tap_code}"
        if hold_key in LAYER_LABELS:
            return f"&lt_ {LAYER_LABELS[hold_key]} {tap_code}"
    raise KeyError(f"Cannot map thumb key ({tap}, {hold}) to zmk.")


def generate_zmk_combo(combo):
    # TODO: Implement combos for ZMK
    return ("0 0", "&trans")


def generate_zmk_layer(layer):
    rows = []
    for row in layer.rows[:3]:
        # Pad to Corne 6-column firmware while authoring a 5-column layout.
        rows.append(
            "&trans "
            + " ".join(map_tap_hold_key_to_zmk(tap, hold) for tap, hold in row)
            + " &trans"
        )
    rows.append(
        " ".join(map_tap_hold_key_to_zmk(tap, hold) for tap, hold in layer.rows[3])
    )
    return "\n".join(rows)


################################################################################
# keymap-drawer YAML parsing


def parse_key_spec(spec):
    """Convert a keymap-drawer LayoutKey (str or mapping) to TapHold."""
    if spec is None:
        return TapHold("", None)
    if isinstance(spec, str):
        return TapHold(spec, None)
    if isinstance(spec, dict):
        tap = normalize_label(spec.get("t", spec.get("tap", spec.get("center", ""))))
        hold = normalize_label(
            spec.get("h", spec.get("hold", spec.get("bottom", "")))
        )
        return TapHold(tap, hold or None)
    raise TypeError(f"Unsupported key spec: {spec!r}")


def flatten_layer_keys(layer_value):
    """Flatten row-grouped keymap-drawer layer lists into a flat key list."""
    keys = []

    def walk(node):
        if isinstance(node, list):
            for item in node:
                walk(item)
        else:
            keys.append(node)

    walk(layer_value)
    return keys


def rows_from_flat_keys(flat_keys, columns=5, thumbs=3):
    """Split a flat 36-key list into 3x10 + thumb row of 6."""
    expected = columns * 2 * 3 + thumbs * 2
    if len(flat_keys) != expected:
        raise ValueError(
            f"Expected {expected} keys for {columns}x3+{thumbs} split, got {len(flat_keys)}"
        )
    rows = []
    idx = 0
    for _ in range(3):
        rows.append([parse_key_spec(k) for k in flat_keys[idx : idx + columns * 2]])
        idx += columns * 2
    rows.append([parse_key_spec(k) for k in flat_keys[idx : idx + thumbs * 2]])
    return rows


def parse_combos(combos_data, layer_names):
    """Best-effort combo parse; unused today but keeps schema room to grow."""
    combos = []
    for combo in combos_data or []:
        key = combo.get("k", combo.get("key", ""))
        if isinstance(key, dict):
            key = key.get("t", key.get("tap", ""))
        triggers = combo.get("tk", combo.get("trigger_keys"))
        if triggers and len(triggers) >= 2:
            a = triggers[0] if isinstance(triggers[0], str) else triggers[0].get("t", "")
            b = triggers[1] if isinstance(triggers[1], str) else triggers[1].get("t", "")
            combos.append(Combo(normalize_label(a), normalize_label(b), normalize_label(key)))
    return combos


def load_layers(keymap_path):
    with open(keymap_path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    layout = data.get("layout", {}).get("ortho_layout", {})
    columns = int(layout.get("columns", 5))
    thumbs = int(layout.get("thumbs", 3))

    layers = []
    for name, value in (data.get("layers") or {}).items():
        flat = flatten_layer_keys(value)
        rows = rows_from_flat_keys(flat, columns=columns, thumbs=thumbs)
        layers.append(Layer(name=name, rows=rows, combos=[]))

    # Attach top-level combos to the first layer for the existing template slots.
    if layers:
        layers[0] = layers[0]._replace(
            combos=parse_combos(data.get("combos"), [l.name for l in layers])
        )
    return layers


################################################################################
# Generate Keymaps


def generate_keymap(layers, template_path, generate_layer_fn, generate_combo_fn):
    with open(template_path, "r", encoding="utf-8") as template_file:
        template = template_file.read()
        combos = []
        for i, layer in enumerate(layers):
            template = template.replace(f"#LAYER_{i}#", generate_layer_fn(layer))
            combos.extend(layer.combos)
        for combo_id in range(5):
            trigger, result = generate_combo_fn(
                combos[combo_id] if combo_id < len(combos) else None
            )
            template = template.replace(f"#COMBO_TRIGGER_{combo_id}#", trigger)
            template = template.replace(f"#COMBO_RESULT_{combo_id}#", result)
        return HEADER + template


def usage():
    print(f"Usage: {sys.argv[0]} qmk|zmk")


def main(type_: str):
    root_dir = os.path.dirname(os.path.abspath(__file__))
    layers = load_layers(os.path.join(root_dir, "keymap.yaml"))
    if type_ == "zmk":
        print(
            generate_keymap(
                layers,
                os.path.join(root_dir, "zmk_template.dtsi"),
                generate_zmk_layer,
                generate_zmk_combo,
            )
        )
    elif type_ == "qmk":
        print(
            generate_keymap(
                layers,
                os.path.join(root_dir, "qmk_template.c"),
                generate_qmk_layer,
                generate_qmk_combo,
            )
        )
    else:
        usage()


if __name__ == "__main__":
    if len(sys.argv) > 1:
        main(sys.argv[1])
    else:
        usage()
