# Reads the keymap grid from `keymap.txt` and generates QMK and ZMK keymaps.
import sys
import os.path
from collections import namedtuple

HEADER = "// This file is automatically generated from keymap.txt\n"

hyp = lambda z, q: (f"LA(LS(LC(LG({z})", "G(S(C(A({q}))))")

# Maps laels from the keymap grid to key press codes in ZMK and QMK.
# "LABEL": ("ZMK CODE", "QMK CODE")
KEY_PRESS_CODES = {
    # Special Keys
    "ESC": ("ESC", "KC_ESC"),
    "RET": ("RET", "KC_ENT"),
    "TAB": ("TAB", "KC_TAB"),
    "SPC": ("SPC", "KC_SPC"),
    "BKSP": ("BKSP", "KC_BSPC"),
    "CMD_RET": ("LG(RET)", "S(KC_ENT)"),
    "ALT_BKSP": ("LA(BKSP)", "A(KC_BSPC)"),
    # Text Navigatioh Keys
    "LEFT": ("LEFT", "KC_LEFT"),
    "RIGHT": ("RIGHT", "KC_RIGHT"),
    "UP": ("UP", "KC_UP"),
    "DOWN": ("DOWN", "KC_DOWN"),
    "WORD_L": ("LA(LEFT)", "A(KC_LEFT)"),
    "WORD_R": ("LA(RIGHT)", "A(KC_RIGHT)"),
    "HOME": ("HOME", "KC_HOME"),
    "END": ("END", "KC_END"),
    # UI Navigation Keys
    "SPC_L": ("LC(LEFT)", "C(KC_LEFT)"),
    "SPC_R": ("LC(RIGHT)", "C(KC_RIGHT)"),
    "NXT_WIN": ("LC(F4)", "C(KC_F4)"),
    # Forward / Backwards (GUI + Bracket)
    "FWD": ("LG(LBKT)", "G(KC_LBRC)"),
    "BCK": ("LG(RBKT)", "G(KC_RBRC)"),
    # Prev / Next Tab (GUI + Shift Bracket)
    "TAB_L": ("LG(LS(LBKT))", "G(S(KC_LBRC))"),
    "TAB_R": ("LG(LS(RBKT))", "G(S(KC_RBRC))"),
    # Umlaut key
    "UML": ("LA(U)", "A(KC_U)"),
    # Symbols
    "`": ("GRAVE", "KC_GRAVE"),
    "~": ("LS(GRAVE)", "KC_TILDE"),
    "!": ("LS(N1)", "KC_EXCLAIM"),
    "@": ("LS(N2)", "KC_AT"),
    "#": ("LS(N3)", "KC_HASH"),
    "$": ("LS(N4)", "KC_DOLLAR"),
    "%": ("LS(N5)", "KC_PERCENT"),
    "^": ("LS(N6)", "KC_CIRCUMFLEX"),
    "&": ("LS(N7)", "KC_AMPERSAND"),
    "*": ("LS(N8)", "KC_ASTERISK"),
    "(": ("LS(N9)", "KC_LEFT_PAREN"),
    ")": ("LS(N0)", "KC_RIGHT_PAREN"),
    "-": ("KP_MINUS", "KC_MINUS"),
    "_": ("LS(MINUS)", "KC_UNDERSCORE"),
    "=": ("EQUAL", "KC_EQUAL"),
    "+": ("LS(EQUAL)", "KC_PLUS"),
    "[": ("LBKT", "KC_LBRC"),
    "{": ("LS(LBKT)", "KC_LCBR"),
    "]": ("RBKT", "KC_RBRC"),
    "}": ("LS(RBKT)", "KC_RCBR"),
    "\\": ("BSLH", "KC_BSLASH"),
    "PIPE": ("LS(BSLH)", "KC_PIPE"),
    ";": ("SEMI", "KC_SCOLON"),
    ":": ("LS(SEMI)", "KC_COLON"),
    "'": ("SQT", "KC_QUOTE"),
    '"': ("LS(SQT)", "KC_DOUBLE_QUOTE"),
    ",": ("COMMA", "KC_COMMA"),
    "<": ("LS(COMMA)", "KC_LEFT_ANGLE_BRACKET"),
    ".": ("DOT", "KC_DOT"),
    ">": ("LS(DOT)", "KC_RIGHT_ANGLE_BRACKET"),
    "/": ("FSLH", "KC_SLASH"),
    "?": ("LS(FSLH)", "KC_QUESTION"),
    # Modifiers
    "CMD": ("LGUI", "KC_LGUI"),
    "SHFT": ("LSHFT", "KC_LSFT"),
    "CTRL": ("LCTRL", "KC_LCTL"),
    "ALT": ("LALT", "KC_LALT"),
}

# Maps labels from the keymap grid to special instructions for ZMK and QMK.
# "LABEL": ("ZMK", "QMK")
SPECIAL_LABELS = {
    # Bluetooth
    "BT_CLR": ("&bt BT_CLR", "KC_NO"),
    "BT_0": ("&bt BT_SEL 0", "KC_NO"),
    "BT_1": ("&bt BT_SEL 1", "KC_NO"),
    "BT_2": ("&bt BT_SEL 2", "KC_NO"),
    "BT_3": ("&bt BT_SEL 3", "KC_NO"),
}

# Maps labels from the keymap grid to layer numbers.
LAYER_LABELS = {
    "RSE": 1,
    "LWR": 2,
    "HYP": 3,
    "ADJ": 4,
    "MOU": 5,
}

# Hold-tap flavors a key may ask for, matching the suffix of the behaviors in
# `zmk_template.dtsi`. Keys default to 'tap preferred', which suits the
# home-row; the thumb keys ask for 'hold preferred'. Sticky keys have a single
# behavior and take no flavor.
FLAVORS = ("tp", "hp")
DEFAULT_FLAVOR = "tp"


################################################################################
# Mapping to QMK


def get_qmk_key_press_code(label):
    if label.startswith('CMD_'):
        return f"G({get_qmk_key_press_code(label[4:])})"
    elif label.startswith('HYP_'):
        return f"G(S(A(C({get_qmk_key_press_code(label[4:])}))))"
    elif len(label) == 1 and (label.isalpha() or label.isdigit()):
        return f"KC_{label}"
    elif label in KEY_PRESS_CODES:
        return KEY_PRESS_CODES[label][1]
    return None


def map_key_label_to_qmk(label):
    code = get_qmk_key_press_code(label)
    if code:
        return code
    elif label in LAYER_LABELS:
        return f"MO({LAYER_LABELS[label]})"
    elif label in SPECIAL_LABELS:
        return SPECIAL_LABELS[label][1]
    elif not label:
        return "KC_NO"
    raise KeyError(f"Cannot map label {label} to qmk.")


def map_key_to_qmk(key):
    if not key.hold:
        return map_key_label_to_qmk(key.tap)
    if not key.tap:
        return map_key_label_to_qmk(key.hold)

    # QMK has no per key hold-tap flavors, so they are ignored here. One shot
    # keycodes are the closest match for sticky keys: they stick on tap and act
    # as a plain modifier or layer shift when held.
    if key.hold in LAYER_LABELS:
        if key.is_sticky:
            return f"OSL({LAYER_LABELS[key.hold]})"
        tap_code = get_qmk_key_press_code(key.tap)
        if tap_code:
            return f"LT({LAYER_LABELS[key.hold]},{tap_code})"
    else:
        hold_code = get_qmk_key_press_code(key.hold)
        if hold_code:
            hold_code = hold_code.replace("KC_", "MOD_")
            if key.is_sticky:
                return f"OSM({hold_code})"
            tap_code = get_qmk_key_press_code(key.tap)
            if tap_code:
                return f"MT({hold_code},{tap_code})"
    raise KeyError(f"Cannot map hold-tap key ({key.tap}, {key.hold}) to qmk.")


def generate_qmk_combo(combo):
    if not combo:
        return ('KC_NO', 'KC_NO')
    return (", ".join((map_key_label_to_qmk(combo.a), map_key_label_to_qmk(combo.b))), map_key_label_to_qmk(combo.result))


def generate_qmk_layer(layer):
    return ",\n".join(
        ", ".join(map_key_to_qmk(key) for key in row) for row in layer.rows
    )


################################################################################
# Mapping to ZMK


def get_zmk_key_press_code(label):
    if label.startswith('CMD_'):
        return f"LG({get_zmk_key_press_code(label[4:])})"
    elif label.startswith('HYP_'):
        return f"LA(LS(LC(LG({get_zmk_key_press_code(label[4:])}))))"
    elif label.isalpha() and len(label) == 1:
        return label
    elif label.isdigit() and len(label) == 1:
        return f"N{label}"
    elif label in KEY_PRESS_CODES:
        return KEY_PRESS_CODES[label][0]
    return None


def map_key_label_to_zmk(label):
    code = get_zmk_key_press_code(label)
    if code:
        return f"&kp {code}"
    elif label in LAYER_LABELS:
        return f"&mo {LAYER_LABELS[label]}"
    elif label in SPECIAL_LABELS:
        return SPECIAL_LABELS[label][0]
    elif not label:
        return "&trans"
    raise KeyError(f"Cannot map label {label} to zmk.")


def map_key_to_zmk(key):
    if not key.hold:
        return map_key_label_to_zmk(key.tap)
    if not key.tap:
        return map_key_label_to_zmk(key.hold)

    # All defined in the ZMK template: mt/lt hold a modifier/layer and are named
    # after their flavor, smt/slt additionally stick it on tap.
    if key.hold in LAYER_LABELS:
        layer = LAYER_LABELS[key.hold]
        if key.is_sticky:
            return f"&slt_ {layer} {layer}"
        tap_code = get_zmk_key_press_code(key.tap)
        if tap_code:
            return f"&lt_{key.flavor or DEFAULT_FLAVOR} {layer} {tap_code}"
    else:
        hold_code = get_zmk_key_press_code(key.hold)
        if hold_code:
            if key.is_sticky:
                return f"&smt_ {hold_code} {hold_code}"
            tap_code = get_zmk_key_press_code(key.tap)
            if tap_code:
                return f"&mt_{key.flavor or DEFAULT_FLAVOR} {hold_code} {tap_code}"
    raise KeyError(f"Cannot map hold-tap key ({key.tap}, {key.hold}) to zmk.")


def generate_zmk_combo(combo):
    # TODO: Implement combos for ZMK
    return ('0 0', '&trans')


def generate_zmk_layer(layer):
    rows = []
    for row in layer.rows[:3]:
        # Add padding since this is a 5 row layout with a 6 row corne firmware
        rows.append(
            "&trans " + " ".join(map_key_to_zmk(key) for key in row) + " &trans"
        )
    rows.append(" ".join(map_key_to_zmk(key) for key in layer.rows[3]))
    return "\n".join(rows)


################################################################################
# Keymap Grid Parsing

# Number of keys in each row of the grid: three rows of ten, then the thumbs.
ROW_SIZES = (10, 10, 10, 6)

# Cell that holds no key, and no hold when used on the hold side of a cell.
BLANK = "_"

COMMENT = "//"

Combo = namedtuple("Combo", ("a", "b", "result"))


class Key(namedtuple("Key", ("tap", "hold", "flavor"))):
    "A single key: what it does when tapped, and what it does when held."

    @property
    def is_sticky(self):
        "Sticky keys repeat their label, e.g. `shft/shft`."
        return bool(self.tap) and self.tap == self.hold


class Layer(namedtuple("Layer", ("name", "rows"))):
    "A named layer, as rows of keys matching ROW_SIZES."


class ParseError(Exception):
    def __init__(self, path, line_number, message):
        super().__init__(f"{path}:{line_number}: {message}")


def split_unescaped(text, separator):
    "Splits on the first unescaped separator, leaving escape sequences intact."
    parts, part, i = [], [], 0
    while i < len(text):
        if text[i] == "\\" and i + 1 < len(text):
            part.append(text[i:i + 2])
            i += 2
        elif text[i] == separator and not parts:
            parts.append("".join(part))
            part = []
            i += 1
        else:
            part.append(text[i])
            i += 1
    parts.append("".join(part))
    return parts


def strip_comment(line):
    i = 0
    while i < len(line):
        if line[i] == "\\" and i + 1 < len(line):
            i += 2
        elif line.startswith(COMMENT, i):
            return line[:i]
        else:
            i += 1
    return line


def unescape(label):
    out, i = [], 0
    while i < len(label):
        if label[i] == "\\" and i + 1 < len(label):
            out.append(label[i + 1])
            i += 2
        else:
            out.append(label[i])
            i += 1
    return "".join(out)


def parse_label(field):
    "Normalizes a label, mapping the blank cell to an empty label."
    return "" if field == BLANK else unescape(field).upper()


class KeymapParser(object):
    "Parses the keymap grid into a list of layers and combos."

    def __init__(self, path):
        self.path = path
        self.line_number = 0
        self.overlays = {}
        self.layers = []
        self.combos = []
        self.block = None
        self.rows = []

    def error(self, message):
        return ParseError(self.path, self.line_number, message)

    def parse(self, source_lines):
        for self.line_number, line in enumerate(source_lines, start=1):
            line = strip_comment(line).strip()
            if not line:
                continue
            keyword, rest = (line.split(None, 1) + [""])[:2]
            if keyword in ("overlay", "layer", "combos"):
                self.end_block()
                self.start_block(keyword, rest.strip())
            elif self.block is None:
                raise self.error(f"expected an overlay, layer or combos block, got {line!r}")
            elif self.block[0] == "combos":
                self.combos.append(self.parse_combo(line.split()))
            else:
                self.rows.append(self.parse_row(line.split()))
        self.end_block()
        self.check_layers()
        return self.layers, self.combos

    def start_block(self, keyword, rest):
        name, separator, overlays = rest.partition(":")
        overlays = [o.strip() for o in overlays.split(",") if o.strip()] if separator else []
        for overlay in overlays:
            if overlay not in self.overlays:
                raise self.error(f"unknown overlay {overlay!r}")
        if overlays and keyword != "layer":
            raise self.error(f"{keyword} blocks cannot use overlays")
        if bool(name) == (keyword == "combos"):
            raise self.error(f"{keyword} blocks take no name" if name
                             else f"{keyword} blocks need a name")
        self.block = (keyword, name.strip(), overlays)
        self.rows = []

    def end_block(self):
        if self.block is None:
            return
        keyword, name, overlays = self.block
        if keyword != "combos":
            if len(self.rows) != len(ROW_SIZES):
                raise self.error(
                    f"{keyword} {name} has {len(self.rows)} rows, expected {len(ROW_SIZES)}"
                )
            if keyword == "overlay":
                self.overlays[name] = self.rows
            else:
                self.layers.append(Layer(name, self.apply_overlays(self.rows, overlays)))
        self.block = None
        self.rows = []

    def apply_overlays(self, rows, overlays):
        "Fills in the hold of every cell that does not define one itself."
        keys = []
        for y, row in enumerate(rows):
            keys.append([])
            for x, (tap, hold, flavor) in enumerate(row):
                if hold is None:
                    # The cell inherits its hold from the overlays it covers,
                    # with the last overlay to cover it taking precedence.
                    for overlay in overlays:
                        _, covered, covered_flavor = self.overlays[overlay][y][x]
                        if covered:
                            hold, flavor = covered, covered_flavor
                keys[-1].append(Key(tap, hold or "", flavor))
        return keys

    def parse_row(self, cells):
        keyword, name, _ = self.block
        row_number = len(self.rows)
        if row_number >= len(ROW_SIZES):
            raise self.error(f"{keyword} {name} has more than {len(ROW_SIZES)} rows")
        if len(cells) != ROW_SIZES[row_number]:
            raise self.error(
                f"row {row_number} of {keyword} {name} has {len(cells)} keys, "
                f"expected {ROW_SIZES[row_number]}"
            )
        if keyword == "overlay":
            # Overlay cells only define the hold of the keys they cover.
            return [Key("", *self.parse_hold(cell)) for cell in cells]
        return [self.parse_key(cell) for cell in cells]

    def parse_key(self, cell):
        "Parses `TAP`, `TAP/HOLD` or `TAP/HOLD:FLAVOR` into a Key."
        tap, hold = (split_unescaped(cell, "/") + [None])[:2]
        if hold is None:
            # A cell without a hold of its own inherits the hold of an overlay,
            # which `apply_overlays` fills in.
            return Key(parse_label(tap), None, None)
        key = Key(parse_label(tap), *self.parse_hold(hold))
        if key.flavor and (key.is_sticky or not key.tap):
            # Only a key that has both a tap and a hold to choose between uses
            # a flavor, so asking for one anywhere else is a mistake.
            raise self.error(f"{cell!r} is not a hold-tap, so it takes no flavor")
        return key

    def parse_hold(self, field):
        "Parses `HOLD` or `HOLD:FLAVOR` into a (hold, flavor) pair."
        hold, flavor = (split_unescaped(field, ":") + [None])[:2]
        if flavor is not None and flavor not in FLAVORS:
            raise self.error(
                f"unknown flavor {flavor!r}, expected one of {', '.join(FLAVORS)}"
            )
        return parse_label(hold), flavor

    def parse_combo(self, cells):
        if len(cells) != 4 or cells[2] != "->":
            raise self.error("expected a combo of the form `KEY KEY -> RESULT`")
        return Combo(*(parse_label(cell) for cell in cells[:2] + cells[3:]))

    def check_layers(self):
        "Layers are referenced by their position, so the order matters."
        for name, index in LAYER_LABELS.items():
            if index >= len(self.layers) or self.layers[index].name.upper() != name:
                raise self.error(
                    f"layer {index} must be named {name.lower()!r}, as it is the "
                    f"layer used by the {name.lower()} hold"
                )


def parse_keymap(path):
    with open(path, "r") as source:
        return KeymapParser(path).parse(source.readlines())


################################################################################
# Generate Keymaps


def generate_keymap(layers, combos, template_path, generate_layer_fn, generate_combo_fn):
    with open(template_path, "r") as template_file:
        template = template_file.read()
        for i, layer in enumerate(layers):
            template = template.replace(f"#LAYER_{i}#", generate_layer_fn(layer))
        for combo_id in range(5):
            (trigger, result) = generate_combo_fn(
                combos[combo_id] if combo_id < len(combos) else None)
            template = template.replace(f"#COMBO_TRIGGER_{combo_id}#", trigger)
            template = template.replace(f"#COMBO_RESULT_{combo_id}#", result)
        return HEADER + template


def usage():
    print(f"Usage: {sys.argv[0]} qmk|zmk")


def main(type: str):
    root_dir = os.path.dirname(__file__)
    layers, combos = parse_keymap(os.path.join(root_dir, "keymap.txt"))
    if type == "zmk":
        print(
            generate_keymap(
                layers,
                combos,
                os.path.join(root_dir, "zmk_template.dtsi"),
                generate_zmk_layer,
                generate_zmk_combo,
            )
        )
    elif type == "qmk":
        print(
            generate_keymap(
                layers,
                combos,
                os.path.join(root_dir, "qmk_template.c"),
                generate_qmk_layer,
                generate_qmk_combo,
            )
        )
    else:
        usage()


if len(sys.argv) > 1:
    main(sys.argv[1])
else:
    usage()
