"""Fill a firmware template with generated layer and combo bindings."""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path

from keymap_generator.parser import Combo, Layer

HEADER = "// This file is automatically generated from keymap.txt\n"

LayerGenerator = Callable[[Layer], str]

# Renders every combo into the one `#COMBOS#` block a template exposes. Combos
# name their trigger keys by the label those keys tap on the default layer, so
# the generator is handed that layer to resolve them against.
CombosGenerator = Callable[[list[Combo], Layer], str]


def generate_keymap(
    layers: list[Layer],
    combos: list[Combo],
    template_path: str | Path,
    generate_layer_fn: LayerGenerator,
    generate_combos_fn: CombosGenerator,
) -> str:
    """Substitute layer and combo placeholders in a firmware template."""
    template = Path(template_path).read_text(encoding="utf-8")
    for i, layer in enumerate(layers):
        template = template.replace(f"#LAYER_{i}#", generate_layer_fn(layer))
    return HEADER + template.replace("#COMBOS#", generate_combos_fn(combos, layers[0]))
