"""Fill a firmware template with generated layer and combo bindings."""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path

from keymap_generator.parser import Combo, Layer

HEADER = "// This file is automatically generated from keymap.txt\n"

# Number of combo slots the templates expose (`#COMBO_TRIGGER_N#` /
# `#COMBO_RESULT_N#`), matching COMBO_COUNT in the QMK config. Slots without a
# matching combo are filled with the generator's "empty" placeholder.
COMBO_SLOTS = 5

LayerGenerator = Callable[[Layer], str]
ComboGenerator = Callable[[Combo | None], tuple[str, str]]


def generate_keymap(
    layers: list[Layer],
    combos: list[Combo],
    template_path: str | Path,
    generate_layer_fn: LayerGenerator,
    generate_combo_fn: ComboGenerator,
) -> str:
    """Substitute layer and combo placeholders in a firmware template."""
    template = Path(template_path).read_text(encoding="utf-8")
    for i, layer in enumerate(layers):
        template = template.replace(f"#LAYER_{i}#", generate_layer_fn(layer))
    for slot in range(COMBO_SLOTS):
        combo = combos[slot] if slot < len(combos) else None
        trigger, result = generate_combo_fn(combo)
        template = template.replace(f"#COMBO_TRIGGER_{slot}#", trigger)
        template = template.replace(f"#COMBO_RESULT_{slot}#", result)
    return HEADER + template
