"""Fill a firmware template with generated layer and combo bindings."""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path

from keymap_generator.parser import Combo, Layer

HEADER = "// This file is automatically generated from keymap.txt\n"

LayerGenerator = Callable[[Layer], str]
ComboGenerator = Callable[[Combo | None], tuple[str, str]]


def generate_keymap(
    layers: list[Layer],
    combos: list[Combo],
    template_path: str | Path,
    generate_layer_fn: LayerGenerator,
    generate_combo_fn: ComboGenerator,
) -> str:
    """Substitute layer and combo placeholders in a firmware template."""
    with open(template_path, encoding="utf-8") as template_file:
        template = template_file.read()
    for i, layer in enumerate(layers):
        template = template.replace(f"#LAYER_{i}#", generate_layer_fn(layer))
    for combo_id in range(5):
        trigger, result = generate_combo_fn(
            combos[combo_id] if combo_id < len(combos) else None
        )
        template = template.replace(f"#COMBO_TRIGGER_{combo_id}#", trigger)
        template = template.replace(f"#COMBO_RESULT_{combo_id}#", result)
    return HEADER + template
